# Generated by Django 5.2.1 on 2025-05-31 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_admintheme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admintheme',
            options={},
        ),
        migrations.RemoveField(
            model_name='admintheme',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='admintheme',
            name='accessibility_suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admintheme',
            name='css_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='admintheme',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admintheme',
            name='js_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='admintheme',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
