# Generated by Django 5.2.1 on 2025-05-31 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_admintheme_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintheme',
            name='js_file',
            field=models.FileField(blank=True, null=True, upload_to='admin_themes_source/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['js'])]),
        ),
        migrations.AddField(
            model_name='admintheme',
            name='scss_file',
            field=models.FileField(blank=True, null=True, upload_to='admin_themes_source/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['scss'])]),
        ),
    ]
