# Generated by Django 5.2.1 on 2025-05-26 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique name for the theme.', max_length=100, unique=True)),
                ('css_url', models.URLField(blank=True, help_text='URL to the custom CSS file for this theme. Must be a valid URL.', null=True, validators=[django.core.validators.URLValidator()])),
                ('js_url', models.URLField(blank=True, help_text='URL to the custom JavaScript file for this theme. Must be a valid URL.', null=True, validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(default=False, help_text='Only one theme can be active at a time.')),
                ('accessibility_suggestions', models.JSONField(blank=True, default=list, help_text='AI-generated accessibility suggestions.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Theme',
                'verbose_name_plural': 'Admin Themes',
            },
        ),
    ]
